#!/usr/bin/env python3
"""merge scripts/l10n/strings_part*.py into app/Sources/Core/LRStrings.inc"""
import glob
import importlib.util
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', 'app', 'Sources', 'Core', 'LRStrings.inc')


def c(s):
    return '"' + s.replace('"', '\\"') + '"'


rows = []
seen = set()
for path in sorted(glob.glob(os.path.join(HERE, 'strings_part*.py'))):
    spec = importlib.util.spec_from_file_location(os.path.basename(path)[:-3], path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    for en, ru, zh in mod.T:
        if en in seen:
            continue
        seen.add(en)
        rows.append('    { %s, %s, %s },' % (c(en), c(ru), c(zh)))
with open(OUT, 'w', encoding='utf-8') as f:
    f.write('/* generated by scripts/l10n/build_inc.py: edit the strings_part files */\n')
    f.write('\n'.join(rows) + '\n')
print('%d entries -> %s' % (len(rows), os.path.normpath(OUT)))
